#!/bin/sh

LOG_LEVEL=${LOG_LEVEL:-''}
CONTAINER_ENGINE=${CONTAINER_ENGINE:-docker}
CONTAINER_HOST_NET=${CONTAINER_HOST_NET:-"false"}
RENOVATE_CLI=${RENOVATE_CLI:-renovate}
RENOVATE_USE_CONTAINER=${RENOVATE_USE_CONTAINER:-"false"}
RENOVATE_SSL_NO_VERIFY=${RENOVATE_SSL_NO_VERIFY:-"false"}
RENOVATE_PLATFORM=${RENOVATE_PLATFORM:-"github"}
RENOVATE_ENDPOINT=${RENOVATE_ENDPOINT:-''}
RENOVATE_TOKEN=${RENOVATE_TOKEN:-''}
RENOVATE_CONFIG_FILE=${RENOVATE_CONFIG_FILE:-''}
RENOVATE_AUTODISCOVER=${RENOVATE_AUTODISCOVER:-"true"}
RENOVATE_ENV_ARGS=''
RENOVATE_REPOS="$@"

if [[ "${LOG_LEVEL}" == "debug" ]]; then
  set -x
fi

if [[ -n "${RENOVATE_ENDPOINT}" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e RENOVATE_ENDPOINT=${RENOVATE_ENDPOINT}"
fi

if [[ "${RENOVATE_SSL_NO_VERIFY}" == "true" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e NODE_TLS_REJECT_UNAUTHORIZED=0 -e GIT_SSL_NO_VERIFY=true"
fi

if [[ "${CONTAINER_HOST_NET}" == "true" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} --network host"
fi

if [[ -n "${LOG_LEVEL}" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e LOG_LEVEL=${LOG_LEVEL}"
fi

if [[ -n "${RENOVATE_REPOS}" ]]; then
  RENOVATE_AUTODISCOVER="false"
fi

if [[ "${RENOVATE_USE_CONTAINER}" == "true" ]]; then
  if [[ -n "${RENOVATE_CONFIG_FILE}" ]]; then
    ${CONTAINER_ENGINE} run --rm \
      -v ${RENOVATE_CONFIG_FILE}:/usr/src/app/config.js:Z \
      -e RENOVATE_PLATFORM="${RENOVATE_PLATFORM}" \
      -e RENOVATE_TOKEN="${RENOVATE_TOKEN}" \
      -e RENOVATE_AUTODISCOVER=${RENOVATE_AUTODISCOVER} \
      ${RENOVATE_ENV_ARGS} renovate/renovate ${RENOVATE_REPOS}
  else
    ${CONTAINER_ENGINE} run --rm \
      -e RENOVATE_PLATFORM="${RENOVATE_PLATFORM}" \
      -e RENOVATE_TOKEN="${RENOVATE_TOKEN}" \
      -e RENOVATE_AUTODISCOVER=${RENOVATE_AUTODISCOVER} \
      ${RENOVATE_ENV_ARGS} renovate/renovate ${RENOVATE_REPOS}
  fi
else
  export RENOVATE_PLATFORM RENOVATE_AUTODISCOVER
  if [[ "${RENOVATE_SSL_NO_VERIFY}" == "true" ]]; then
    export NODE_TLS_REJECT_UNAUTHORIZED="0" GIT_SSL_NO_VERIFY="true"
  fi
  if [[ -n "${RENOVATE_CONFIG_FILE}" ]]; then
    export RENOVATE_CONFIG_FILE
  fi
  if [[ -n "${LOG_LEVEL}" ]]; then
    export LOG_LEVEL
  fi
  ${RENOVATE_CLI} --token ${RENOVATE_TOKEN} ${RENOVATE_REPOS}
fi
