#!/bin/sh

LOG_LEVEL=${LOG_LEVEL:-''}
CONTAINER_ENGINE=${CONTAINER_ENGINE:-docker}
RENOVATE_CLI=${RENOVATE_CLI:-renovate}
RENOVATE_USE_CONTAINER=${RENOVATE_USE_CONTAINER:-"false"}
RENOVATE_SSL_NO_VERIFY=${RENOVATE_SSL_NO_VERIFY:-"false"}
RENOVATE_PLATFORM=${RENOVATE_PLATFORM:-"github"}
RENOVATE_ENDPOINT=${RENOVATE_ENDPOINT:-''}
RENOVATE_TOKEN=${RENOVATE_TOKEN:-''}
RENOVATE_AUTODISCOVER="true"
RENOVATE_ENV_ARGS=''
RENOVATE_REPOS="$@"

if [[ "${LOG_LEVEL}" == "debug" ]]; then
  set -x
fi

if [[ -n "${RENOVATE_ENDPOINT}" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e RENOVATE_ENDPOINT=${RENOVATE_ENDPOINT}"
fi

if [[ "${RENOVATE_SSL_NO_VERIFY}" == "true" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e NODE_TLS_REJECT_UNAUTHORIZED=0 -e GIT_SSL_NO_VERIFY=true"
fi

if [[ -n "${LOG_LEVEL}" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e LOG_LEVEL=${LOG_LEVEL}"
fi

if [[ -n "${RENOVATE_REPOS}" ]]; then
  RENOVATE_AUTODISCOVER="false"
fi

if [[ "${RENOVATE_USE_CONTAINER}" == "true" ]]; then
  ${CONTAINER_ENGINE} run --rm \
    -e RENOVATE_PLATFORM="${RENOVATE_PLATFORM}" \
    -e RENOVATE_TOKEN="${RENOVATE_TOKEN}" \
    -e RENOVATE_AUTODISCOVER=${RENOVATE_AUTODISCOVER} \
    ${RENOVATE_ENV_ARGS} renovate/renovate ${RENOVATE_REPOS}
else
  export RENOVATE_PLATFORM RENOVATE_AUTODISCOVER LOG_LEVEL
  if [[ "${RENOVATE_SSL_NO_VERIFY}" == "true" ]]; then
    export NODE_TLS_REJECT_UNAUTHORIZED="0" GIT_SSL_NO_VERIFY="true"
  fi
  ${RENOVATE_CLI} --token ${RENOVATE_TOKEN} ${RENOVATE_REPOS}
fi
