#!/bin/sh

CONTAINER_ENGINE=${CONTAINER_ENGINE:-docker}
RENOVATE_SSL_NO_VERIFY=${RENOVATE_SSL_NO_VERIFY:-"false"}
RENOVATE_PLATFORM=${RENOVATE_PLATFORM:-"github"}
RENOVATE_ENDPOINT=${RENOVATE_ENDPOINT:-''}
RENOVATE_TOKEN=${RENOVATE_TOKEN:-''}
RENOVATE_AUTODISCOVER="true"
RENOVATE_ENV_ARGS=''
RENOVATE_REPOS="$@"

if [[ -n "${RENOVATE_ENDPOINT}" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e RENOVATE_ENDPOINT=${RENOVATE_ENDPOINT}"
fi

if [[ "${RENOVATE_SSL_NO_VERIFY}" == "true" ]]; then
  RENOVATE_ENV_ARGS="${RENOVATE_ENV_ARGS} -e NODE_TLS_REJECT_UNAUTHORIZED=\"0\" -e GIT_SSL_NO_VERIFY=\"true\""
fi

if [[ -n "${RENOVATE_REPOS}" ]]; then
  RENOVATE_AUTODISCOVER="false"
fi

${CONTAINER_ENGINE} run --rm \
  -e RENOVATE_PLATFORM="${RENOVATE_PLATFORM}" \
  -e RENOVATE_TOKEN="${RENOVATE_TOKEN}" \
  -e RENOVATE_AUTODISCOVER=${RENOVATE_AUTODISCOVER} \
  ${RENOVATE_ENV_ARGS} renovate/renovate ${RENOVATE_REPOS}
