image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Test Fedora Setup'
          script:
            - sh test/fedora/test.sh installers/fedora_setup.sh
          services:
            - docker
          caches:
            - docker
      - step:
          name: 'Test Rocky 8 Setup'
          script:
            - sh test/rocky/el8/test.sh installers/rocky_setup.sh
          services:
            - docker
          caches:
            - docker
      - step:
          name: 'Test Rocky 9 Setup'
          script:
            - sh test/rocky/el9/test.sh installers/rocky_setup.sh
          services:
            - docker
          caches:
            - docker
      - step:
          name: 'Test Debian Buster Setup'
          script:
            - sh test/debian/buster/test.sh installers/debian_setup.sh
          services:
            - docker
          caches:
            - docker
      - step:
          name: 'Test Debian Bullseye Setup'
          script:
            - sh test/debian/bullseye/test.sh installers/debian_setup.sh
          services:
            - docker
          caches:
            - docker
